<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="http://maven.apache.org/POM/4.0.0"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <artifactId>toy-application</artifactId>
  <dependencies>


    <dependency>
      <artifactId>toy-domain</artifactId>
      <groupId>locser</groupId>
      <version>${project.version}</version>
    </dependency>

    <dependency>
      <artifactId>toy-infrastructure</artifactId>
      <groupId>locser</groupId>
      <version>${project.version}</version>
    </dependency>


    <dependency>
      <artifactId>spring-boot-starter-validation</artifactId>
      <groupId>org.springframework.boot</groupId>
    </dependency>


  </dependencies>

  <groupId>locser</groupId>
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <artifactId>x-toy</artifactId>
    <groupId>locser</groupId>
    <version>0.0.1-SNAPSHOT</version>
  </parent>

  <properties>
    <maven.compiler.source>21</maven.compiler.source>
    <maven.compiler.target>21</maven.compiler.target>
  </properties>

  <version>0.0.1-SNAPSHOT</version>

</project>