<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="http://maven.apache.org/POM/4.0.0"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <artifactId>toy-controller</artifactId>
  <dependencies>
    <dependency>
      <artifactId>common</artifactId>
      <groupId>locser</groupId>
      <version>0.0.1-SNAPSHOT</version>
    </dependency>

    <dependency>
      <artifactId>toy-application</artifactId>
      <groupId>locser</groupId>
      <version>${project.version}</version>
    </dependency>

    <dependency>
      <artifactId>toy-domain</artifactId>
      <groupId>locser</groupId>
      <version>${project.version}</version>
    </dependency>

    <dependency>
      <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
      <groupId>org.springdoc</groupId>
      <version>2.5.0</version>
    </dependency>

    <!-- https://mvnrepository.com/artifact/org.springdoc/springdoc-openapi-ui -->
    <dependency>
      <artifactId>springdoc-openapi-ui</artifactId>
      <groupId>org.springdoc</groupId>
      <version>1.7.0</version>
    </dependency>
    <dependency>
      <artifactId>toy-application</artifactId>
      <groupId>locser</groupId>
      <scope>compile</scope>
      <version>1.0-SNAPSHOT</version>
    </dependency>
    <dependency>
      <artifactId>spring-boot-starter-web</artifactId>
      <groupId>org.springframework.boot</groupId>
    </dependency>
    <dependency>
      <artifactId>jackson-databind</artifactId>
      <groupId>com.fasterxml.jackson.core</groupId>
    </dependency>

    <!-- https://mvnrepository.com/artifact/org.springframework.security/spring-security-oauth2-client -->
    <!--    <dependency>-->
    <!--      <artifactId>spring-security-oauth2-client</artifactId>-->
    <!--      <groupId>org.springframework.security</groupId>-->
    <!--      <version>6.4.4</version>-->
    <!--    </dependency>-->

  </dependencies>

  <groupId>locser</groupId>
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <artifactId>x-toy</artifactId>
    <groupId>locser</groupId>
    <version>0.0.1-SNAPSHOT</version>
  </parent>

  <properties>
    <maven.compiler.source>21</maven.compiler.source>
    <maven.compiler.target>21</maven.compiler.target>
  </properties>

  <version>0.0.1-SNAPSHOT</version>
</project>